baseURL: "https://sinangncgl.github.io"
languageCode: en-us
title: Sinan Gençoğlu blog
theme: PaperMod

enableEmoji: true

params:
  author: Sinan Gençoğlu
  homeInfoParams:
    Title: "Hey Ho!"
    Content: >
      Welcome!

  socialIcons:
    - name: Github
      url: "https://github.com/SinanGncgl"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/sinan-gencoglu/"

  ShowReadingTime: true
  ShowShareButtons: true
