baseURL: "https://sinangncgl.github.io"
languageCode: en-us
title: Personal Website
theme: PaperMod

enableEmoji: true

params:
  author: Sinan Gençoğlu
  homeInfoParams:
    Title: "Hey Ho!"
    Content: >
      Welcome!

  socialIcons:
    - name: Github
      url: "https://github.com/SinanGncgl"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/sinan-gencoglu/"

  ShowReadingTime: true
  ShowShareButtons: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
