baseURL = 'https://sinangncgl.github.io'
languageCode = 'en-us'
title = 'Sinan Gencoglu - Blog'
theme = 'PaperMod'

[params]
  enableGoogleAnalytics = true

[params.analytics.google]
  siteID = "G-ER8M6KT8WP"